// Pulls the live state of the sapinsapin org from the Hugging Face Hub API and
// writes it to src/data/hubSnapshot.js.
//
// This runs at BUILD time on purpose. The Hub API replies with
// `access-control-allow-origin: https://huggingface.co`, so a browser on
// sapinsapin.ai cannot call it directly — a client-side fetch would be blocked
// by CORS. Syncing on build keeps the page honest on every deploy without a
// proxy, and the generated file is the single source of numbers so the editorial
// copy in catalog.js never has to be hand-updated.
//
// Note on `downloads`: the Hub reports downloads over the last 30 days, which is
// what the org's own dashboard Space labels "Downloads (30d)". Keep that wording
// wherever the number is shown.

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

const org = 'sapinsapin'
const outputPath = resolve('src/data/hubSnapshot.js')

// lastModified and pipeline_tag are only returned when explicitly expanded —
// without this the list endpoint omits them and every date comes back null.
// The field sets differ per kind: pipeline_tag is models-only and asking for it
// on datasets returns HTTP 400.
const expandFields = {
  models: ['downloads', 'likes', 'lastModified', 'private', 'gated', 'pipeline_tag'],
  datasets: ['downloads', 'likes', 'lastModified', 'private', 'gated', 'tags'],
}

async function listRepos(kind) {
  const expand = expandFields[kind].map((field) => `expand[]=${field}`).join('&')
  const url = `https://huggingface.co/api/${kind}?author=${org}&limit=1000&${expand}`
  const response = await fetch(url, { headers: { accept: 'application/json' } })
  if (!response.ok) throw new Error(`${kind}: HTTP ${response.status}`)
  return response.json()
}

const shortName = (id) => id.split('/').pop()

// The Hub carries the license as a `license:<id>` tag. Only some repos set one,
// and `other` means "not one of the SPDX choices" — which is less informative
// than the name the dataset card actually uses, so it is reported as null and
// the editorial value stands.
const licenseOf = (tags = []) => {
  const tag = tags.find((t) => t.startsWith('license:'))
  const value = tag ? tag.slice('license:'.length) : null
  return value && value !== 'other' ? value : null
}

// Hub pipeline tags are slugs; a couple are too long to read well as a chip.
const taskLabels = {
  'automatic-speech-recognition': 'Speech recognition',
  'text-to-speech': 'Text to speech',
  'text-generation': 'Text generation',
  'audio-to-audio': 'Audio to audio',
  'image-text-to-text': 'Image-text to text',
}
const labelTask = (tag) => {
  if (!tag) return null
  if (taskLabels[tag]) return taskLabels[tag]
  const words = tag.replace(/-/g, ' ')
  return words.charAt(0).toUpperCase() + words.slice(1)
}
const day = (value) => (value ? value.slice(0, 10) : null)

const [models, datasets] = await Promise.all([listRepos('models'), listRepos('datasets')])

const modelRows = models
  .map((model) => ({
    name: shortName(model.id),
    task: labelTask(model.pipeline_tag),
    downloads: model.downloads ?? 0,
    likes: model.likes ?? 0,
    updated: day(model.lastModified),
  }))
  .sort((a, b) => b.downloads - a.downloads)

const datasetRows = datasets
  .map((dataset) => ({
    id: shortName(dataset.id),
    downloads: dataset.downloads ?? 0,
    likes: dataset.likes ?? 0,
    updated: day(dataset.lastModified),
    gated: Boolean(dataset.gated),
    license: licenseOf(dataset.tags),
  }))
  .sort((a, b) => b.downloads - a.downloads)

const totals = {
  models: modelRows.length,
  datasets: datasetRows.length,
  modelDownloads: modelRows.reduce((sum, row) => sum + row.downloads, 0),
  datasetDownloads: datasetRows.reduce((sum, row) => sum + row.downloads, 0),
}

const file = `// Generated by scripts/sync-catalog.mjs — do not edit by hand.
// Live state of https://huggingface.co/${org}, read from the public Hub API.
// \`downloads\` is the Hub's 30-day count, matching the org dashboard Space.
export const syncedAt = ${JSON.stringify(new Date().toISOString().slice(0, 10))}
export const hubTotals = ${JSON.stringify(totals)}
export const hubModels = ${JSON.stringify(modelRows, null, 2)}
export const hubDatasets = ${JSON.stringify(datasetRows, null, 2)}
`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, file)
console.log(
  `synced ${totals.models} models (${totals.modelDownloads.toLocaleString()} dl/30d) · ` +
  `${totals.datasets} datasets (${totals.datasetDownloads.toLocaleString()} dl/30d)`,
)
